import json
from typing import Dict, Optional, List, Any
from colors import BOLD, CYAN, RESET
from alive_progress import alive_bar
from llm_sdk import Small_LLM_Model  # type: ignore


class ModelManager:
    """Singleton class to manage LLM loading and tokenizer vocabulary.

    Attributes:
        _instance: The singleton instance of the Small_LLM_Model.
        id_to_token (Dict[int, str]): Mapping from token IDs to string tokens.
        call_count (int): Counter for the number of generation calls made.
    """
    _instance: Optional[Small_LLM_Model] = None
    id_to_token: Dict[int, str] = {}
    call_count: int = 0

    def __new__(cls) -> Small_LLM_Model:
        """Creates or returns the existing Small_LLM_Model instance.

        Returns:
            Small_LLM_Model: The loaded model instance.
        """
        if cls._instance is None:
            print(f"\n{CYAN}Loading LLM into memory...{RESET}")
            cls._instance = Small_LLM_Model()

            vocab_path = cls._instance.get_path_to_tokenizer_file()
            with open(vocab_path, 'r', encoding='utf-8') as f:
                data = json.load(f)

                cls.id_to_token = {}

                if "model" in data and "vocab" in data["model"]:
                    for token, token_id in data["model"]["vocab"].items():
                        cls.id_to_token[int(token_id)] = token

                if "added_tokens" in data:
                    for item in data["added_tokens"]:
                        cls.id_to_token[int(item["id"])] = item["content"]
        return cls._instance


def _ids_generator(prompt: str,
                   stop_str: Optional[str] = None,
                   is_json: bool = False) -> Any:
    """Generates text from the model token by token with specific constraints.

    Args:
        prompt: The input text for the model.
        stop_str: A string that triggers the stop of generation
        if encountered.
        is_json: If True, uses bracket counting to ensure JSON
        structural integrity.

    Returns:
        str: The decoded and cleaned string generated by the model.
    """
    model: Small_LLM_Model = ModelManager()
    current_ids: List[int] = model.encode(prompt).tolist()[0]
    generated: List[int] = []
    bracket_count = 0
    ModelManager.call_count += 1
    current_iter = ModelManager.call_count

    with alive_bar(title=f"{BOLD}{CYAN}[{current_iter}] LLM Thinking{RESET}",
                   total=None,
                   bar=None,
                   spinner="dots_waves") as bar:
        while True:
            current_iter += 1
            logits = model.get_logits_from_input_ids(current_ids + generated)
            next_id = logits.index(max(logits))

            if next_id in [151643, 151645]:
                break

            token_str = ModelManager.id_to_token.get(next_id, "")
            generated.append(next_id)
            bar()

            if stop_str and stop_str in token_str:
                break

            if is_json:
                bracket_count += token_str.count("{")
                bracket_count -= token_str.count("}")
                if bracket_count < 0:
                    break

            if len(generated) > 200:
                break

    decoded = model.decode(generated).strip()

    if stop_str and stop_str in decoded:
        decoded = decoded.split(stop_str)[0]

    if is_json and "}" in decoded:
        last_bracket = decoded.rfind("}")
        decoded = decoded[:last_bracket]

    return decoded.strip()


def constrained_search(sys_prompt: str, user_query: str) -> str:
    """Performs a structured search to generate valid function call JSON.

    Args:
        sys_prompt: The system instructions and tool definitions.
        user_query: The specific user request.

    Returns:
        str: A string in JSON format containing prompt, name, and parameters.
    """
    safe_query = user_query.replace('"', '\\"')
    context = sys_prompt + f'{{"prompt": "{safe_query}", "name": "'

    # 2. Генерируем только имя (до первой кавычки)
    fn_name = _ids_generator(context, stop_str='"')

    context += fn_name + '", "parameters": '

    # 4. Генерируем параметры (до закрытия JSON)
    params = _ids_generator(context, is_json=True)

    # 5. Возвращаем готовую строку
    return (f'{{"prompt": "{safe_query}",'
            f' "name": "{fn_name}",'
            f' "parameters": {params}}}')
